name: FTP Deploy

on: [push]

jobs:
  ftp-deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE

    # Add any setup steps that your project requires here...

    - name: Upload files to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        # Optional deployment arguments
        local-dir: ./
        server-dir: ${{ secrets.FTP_PATH }}
        # Set to 'true' if you want the action to delete files in the server directory that are not present in the local directory
        dangerous-clean-slate: false

